apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infras/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nhannt1905/react-app
      context: front-end
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: nhannt1905/comment-service
      context: back-end/comment-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nhannt1905/post-service
      context: back-end/post-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nhannt1905/moderation-service
      context: back-end/moderation-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nhannt1905/query-service
      context: back-end/query-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nhannt1905/event-bus
      context: back-end/event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"